spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  cloud:
    stream:
      rabbit:
        bindings:
          messaging-channel:
            destination: messaging-exchange
            group: messaging-group
